import { LanguageConfig, SupportedLanguage } from '../types';

export const ALL_SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  'ar',
  'bn',
  'cs',
  'de',
  'el',
  'en',
  'es',
  'fa',
  'fr',
  'hi',
  'hu',
  'id',
  'it',
  'ja',
  'ko',
  'ms',
  'nl',
  'pl',
  'pt',
  'ro',
  'ru',
  'sk',
  'sr',
  'sv',
  'th',
  'tr',
  'uk',
  'vi',
  'zh-Hans',
];

export const LANGUAGES: Record<SupportedLanguage, LanguageConfig> = {
  ar: {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    dir: 'rtl',
    font: 'Amiri',
    active: true,
    flag: '🇸🇦',
  },
  bn: {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇧🇩',
  },
  cs: {
    code: 'cs',
    name: 'Czech',
    nativeName: 'Čeština',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇨🇿',
  },
  de: {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇩🇪',
  },
  el: {
    code: 'el',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇬🇷',
  },
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇺🇸',
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇪🇸',
  },
  fa: {
    code: 'fa',
    name: 'Persian',
    nativeName: 'فارسی',
    dir: 'rtl',
    font: 'Amiri',
    active: true,
    flag: '🇮🇷',
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇫🇷',
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇮🇳',
  },
  hu: {
    code: 'hu',
    name: 'Hungarian',
    nativeName: 'Magyar',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇭🇺',
  },
  id: {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇮🇩',
  },
  it: {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇮🇹',
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇯🇵',
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇰🇷',
  },
  ms: {
    code: 'ms',
    name: 'Malay',
    nativeName: 'Bahasa Melayu',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇲🇾',
  },
  nl: {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇳🇱',
  },
  pl: {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇵🇱',
  },
  pt: {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇧🇷',
  },
  ro: {
    code: 'ro',
    name: 'Romanian',
    nativeName: 'Română',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇷🇴',
  },
  ru: {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇷🇺',
  },
  sk: {
    code: 'sk',
    name: 'Slovak',
    nativeName: 'Slovenčina',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇸🇰',
  },
  sr: {
    code: 'sr',
    name: 'Serbian',
    nativeName: 'Srpski',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇷🇸',
  },
  sv: {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇸🇪',
  },
  th: {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇹🇭',
  },
  tr: {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇹🇷',
  },
  uk: {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇺🇦',
  },
  vi: {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇻🇳',
  },
  'zh-Hans': {
    code: 'zh-Hans',
    name: 'Simplified Chinese',
    nativeName: '简体中文',
    dir: 'ltr',
    font: 'Plus Jakarta Sans',
    active: true,
    flag: '🇨🇳',
  },
};

export function isSupportedLocale(str: string): str is SupportedLanguage {
  return ALL_SUPPORTED_LANGUAGES.includes(str as SupportedLanguage);
}

export function getLanguageConfig(locale: SupportedLanguage): LanguageConfig {
  return LANGUAGES[locale] || LANGUAGES.en;
}

export function isRtlLocale(locale: string): boolean {
  return locale === 'ar' || locale === 'fa';
}
